global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Opc.Ua;
global using Opc.Ua.Client;
global using Opc.Ua.Configuration;
global using OpcUa.Client.Contracts;
global using OpcUa.Client.Infrastructiure;
global using OpcUa.Client.Services;
global using OpcUa.Client.Models;
